name=T-HMI-C64
version=1.1.1
author=retroelec42@gmail.com
maintainer=retroelec42@gmail.com
sentence=C64 Emulator for ESP32-S3 (and ESP32) with Android BLE keyboard or Web keyboard
paragraph=The emulator is running on the Lilygo T-HMI development board, the Lilygo T-Display S3 AMOLED, the ESP32-S3-LCD-2.8 from Waveshare and the ESP32 CYD board. The emulator is also running on an ESP32-S3-WROOM with a 64x64 LED matrix panel.
url=https://github.com/retroelec/T-HMI-C64
architectures=esp32s3,esp32,linux,mac,windows
