#include "../Config.h"
#ifdef USE_SDL_KEYBOARD
#include "SDLKeymap.h"

// definitions for a swiss german keyboard
// -> adapt for your keyboard
const std::map<KeySpec, CodeTriple> keyMap = {
    // unmodified
    {{SDLK_ESCAPE, false, false, false}, C64_KEYCODE_BREAK},
    {{SDLK_RETURN, false, false, false}, C64_KEYCODE_RETURN},
    {{SDLK_BACKSPACE, false, false, false}, C64_KEYCODE_BACKSPACE},
    {{SDLK_SPACE, false, false, false}, C64_KEYCODE_SPACE},
    {{SDLK_0, false, false, false}, C64_KEYCODE_0},
    {{SDLK_1, false, false, false}, C64_KEYCODE_1},
    {{SDLK_2, false, false, false}, C64_KEYCODE_2},
    {{SDLK_3, false, false, false}, C64_KEYCODE_3},
    {{SDLK_4, false, false, false}, C64_KEYCODE_4},
    {{SDLK_5, false, false, false}, C64_KEYCODE_5},
    {{SDLK_6, false, false, false}, C64_KEYCODE_6},
    {{SDLK_7, false, false, false}, C64_KEYCODE_7},
    {{SDLK_8, false, false, false}, C64_KEYCODE_8},
    {{SDLK_9, false, false, false}, C64_KEYCODE_9},
    {{SDLK_w, false, false, false}, C64_KEYCODE_W},
    {{SDLK_a, false, false, false}, C64_KEYCODE_A},
    {{SDLK_z, false, false, false}, C64_KEYCODE_Z},
    {{SDLK_s, false, false, false}, C64_KEYCODE_S},
    {{SDLK_e, false, false, false}, C64_KEYCODE_E},
    {{SDLK_r, false, false, false}, C64_KEYCODE_R},
    {{SDLK_d, false, false, false}, C64_KEYCODE_D},
    {{SDLK_c, false, false, false}, C64_KEYCODE_C},
    {{SDLK_f, false, false, false}, C64_KEYCODE_F},
    {{SDLK_t, false, false, false}, C64_KEYCODE_T},
    {{SDLK_x, false, false, false}, C64_KEYCODE_X},
    {{SDLK_y, false, false, false}, C64_KEYCODE_Y},
    {{SDLK_g, false, false, false}, C64_KEYCODE_G},
    {{SDLK_b, false, false, false}, C64_KEYCODE_B},
    {{SDLK_h, false, false, false}, C64_KEYCODE_H},
    {{SDLK_u, false, false, false}, C64_KEYCODE_U},
    {{SDLK_v, false, false, false}, C64_KEYCODE_V},
    {{SDLK_i, false, false, false}, C64_KEYCODE_I},
    {{SDLK_j, false, false, false}, C64_KEYCODE_J},
    {{SDLK_m, false, false, false}, C64_KEYCODE_M},
    {{SDLK_k, false, false, false}, C64_KEYCODE_K},
    {{SDLK_o, false, false, false}, C64_KEYCODE_O},
    {{SDLK_n, false, false, false}, C64_KEYCODE_N},
    {{SDLK_p, false, false, false}, C64_KEYCODE_P},
    {{SDLK_l, false, false, false}, C64_KEYCODE_L},
    {{SDLK_MINUS, false, false, false}, C64_KEYCODE_MINUS},
    {{SDLK_PERIOD, false, false, false}, C64_KEYCODE_PERIOD},
    {{SDLK_COMMA, false, false, false}, C64_KEYCODE_COMMA},
    {{SDLK_q, false, false, false}, C64_KEYCODE_Q},
    {{SDLK_DOLLAR, false, false, false}, C64_KEYCODE_DOLLAR},
    {{SDLK_LESS, false, false, false}, C64_KEYCODE_LESS},
    {{SDLK_RIGHT, false, false, false}, C64_KEYCODE_RIGHT},
    {{SDLK_LEFT, false, false, false}, C64_KEYCODE_LEFT},
    {{SDLK_DOWN, false, false, false}, C64_KEYCODE_DOWN},
    {{SDLK_UP, false, false, false}, C64_KEYCODE_UP},
    {{SDLK_F1, false, false, false}, C64_KEYCODE_F1},
    {{SDLK_F3, false, false, false}, C64_KEYCODE_F3},
    {{SDLK_F5, false, false, false}, C64_KEYCODE_F5},
    {{SDLK_F7, false, false, false}, C64_KEYCODE_F7},
    {{SDLK_QUOTE, false, false, false}, C64_KEYCODE_QUOTE},
    {{SDLK_HOME, false, false, false}, C64_KEYCODE_HOME},
    {{SDLK_DELETE, false, false, false}, C64_KEYCODE_DEL},
    {{246, false, false, false}, C64_KEYCODE_AT},        // 246 = ö
    {{228, false, false, false}, C64_KEYCODE_LEFTARROW}, // 228 = ä
    {{252, false, false, false}, C64_KEYCODE_LEFTBRACKET},
    {{1073741824, false, false, false}, C64_KEYCODE_RIGHTBRACKET},
    {{1073741824, false, false, false}, C64_KEYCODE_RIGHTBRACKET},
    // shift
    {{SDLK_w, true, false, false}, C64_KEYCODE_W_SHIFT},
    {{SDLK_a, true, false, false}, C64_KEYCODE_A_SHIFT},
    {{SDLK_z, true, false, false}, C64_KEYCODE_Z_SHIFT},
    {{SDLK_s, true, false, false}, C64_KEYCODE_S_SHIFT},
    {{SDLK_e, true, false, false}, C64_KEYCODE_E_SHIFT},
    {{SDLK_r, true, false, false}, C64_KEYCODE_R_SHIFT},
    {{SDLK_d, true, false, false}, C64_KEYCODE_D_SHIFT},
    {{SDLK_c, true, false, false}, C64_KEYCODE_C_SHIFT},
    {{SDLK_f, true, false, false}, C64_KEYCODE_F_SHIFT},
    {{SDLK_t, true, false, false}, C64_KEYCODE_T_SHIFT},
    {{SDLK_x, true, false, false}, C64_KEYCODE_X_SHIFT},
    {{SDLK_y, true, false, false}, C64_KEYCODE_Y_SHIFT},
    {{SDLK_g, true, false, false}, C64_KEYCODE_G_SHIFT},
    {{SDLK_b, true, false, false}, C64_KEYCODE_B_SHIFT},
    {{SDLK_h, true, false, false}, C64_KEYCODE_H_SHIFT},
    {{SDLK_u, true, false, false}, C64_KEYCODE_U_SHIFT},
    {{SDLK_v, true, false, false}, C64_KEYCODE_V_SHIFT},
    {{SDLK_i, true, false, false}, C64_KEYCODE_I_SHIFT},
    {{SDLK_j, true, false, false}, C64_KEYCODE_J_SHIFT},
    {{SDLK_m, true, false, false}, C64_KEYCODE_M_SHIFT},
    {{SDLK_k, true, false, false}, C64_KEYCODE_K_SHIFT},
    {{SDLK_o, true, false, false}, C64_KEYCODE_O_SHIFT},
    {{SDLK_n, true, false, false}, C64_KEYCODE_N_SHIFT},
    {{SDLK_p, true, false, false}, C64_KEYCODE_P_SHIFT},
    {{SDLK_l, true, false, false}, C64_KEYCODE_L_SHIFT},
    {{SDLK_q, true, false, false}, C64_KEYCODE_Q_SHIFT},
    {{SDLK_2, true, false, false}, C64_KEYCODE_QUOTEDBL},
    {{SDLK_5, true, false, false}, C64_KEYCODE_PERCENT},
    {{SDLK_6, true, false, false}, C64_KEYCODE_AMPERSAND},
    {{SDLK_8, true, false, false}, C64_KEYCODE_LEFTPAREN},
    {{SDLK_9, true, false, false}, C64_KEYCODE_RIGHTPAREN},
    {{SDLK_LESS, true, false, false}, C64_KEYCODE_GREATER},
    {{SDLK_QUOTE, true, false, false}, C64_KEYCODE_QUESTION},
    {{SDLK_1, true, false, false}, C64_KEYCODE_PLUS},
    {{SDLK_3, true, false, false}, C64_KEYCODE_ASTERISK},
    {{SDLK_7, true, false, false}, C64_KEYCODE_SLASH},
    {{SDLK_0, true, false, false}, C64_KEYCODE_EQUALS},
    {{SDLK_PERIOD, true, false, false}, C64_KEYCODE_COLON},
    {{SDLK_COMMA, true, false, false}, C64_KEYCODE_SEMICOLON},
    {{SDLK_DOLLAR, true, false, false}, C64_KEYCODE_POUND},
    {{SDLK_DELETE, true, false, false}, C64_KEYCODE_INS},
    {{SDLK_HOME, true, false, false}, C64_KEYCODE_CLR},
    {{1073741824, true, false, false}, C64_KEYCODE_EXCLAIM},
    {{246, true, false, false}, C64_KEYCODE_HASH},
    {{228, true, false, false}, C64_KEYCODE_UPARROW},
    // ctrl
    {{SDLK_0, false, true, false}, C64_KEYCODE_0_CTRL},
    {{SDLK_1, false, true, false}, C64_KEYCODE_1_CTRL},
    {{SDLK_2, false, true, false}, C64_KEYCODE_2_CTRL},
    {{SDLK_3, false, true, false}, C64_KEYCODE_3_CTRL},
    {{SDLK_4, false, true, false}, C64_KEYCODE_4_CTRL},
    {{SDLK_5, false, true, false}, C64_KEYCODE_5_CTRL},
    {{SDLK_6, false, true, false}, C64_KEYCODE_6_CTRL},
    {{SDLK_7, false, true, false}, C64_KEYCODE_7_CTRL},
    {{SDLK_8, false, true, false}, C64_KEYCODE_8_CTRL},
    {{SDLK_9, false, true, false}, C64_KEYCODE_9_CTRL},
    // commodore
    {{SDLK_1, false, false, true}, C64_KEYCODE_1_COMMODORE},
    {{SDLK_2, false, false, true}, C64_KEYCODE_2_COMMODORE},
    {{SDLK_3, false, false, true}, C64_KEYCODE_3_COMMODORE},
    {{SDLK_4, false, false, true}, C64_KEYCODE_4_COMMODORE},
    {{SDLK_5, false, false, true}, C64_KEYCODE_5_COMMODORE},
    {{SDLK_6, false, false, true}, C64_KEYCODE_6_COMMODORE},
    {{SDLK_7, false, false, true}, C64_KEYCODE_7_COMMODORE},
    {{SDLK_8, false, false, true}, C64_KEYCODE_8_COMMODORE},
};
#endif
