#include "../Config.h"
#ifdef USE_SDL_KEYBOARD
#include "SDLKeymap.h"

// definitions for a swiss german keyboard
// -> adapt for your keyboard
// allowed modifiers: shift, right alt (alt gr)
const std::map<KeySpec, CodeTripleS> keyMap = {
    // unmodified
    {{SDLK_ESCAPE, false, false}, C64_KEYCODE_BREAK},
    {{SDLK_RETURN, false, false}, C64_KEYCODE_RETURN},
    {{SDLK_BACKSPACE, false, false}, C64_KEYCODE_BACKSPACE},
    {{SDLK_SPACE, false, false}, C64_KEYCODE_SPACE},
    {{SDLK_0, false, false}, C64_KEYCODE_0},
    {{SDLK_1, false, false}, C64_KEYCODE_1},
    {{SDLK_2, false, false}, C64_KEYCODE_2},
    {{SDLK_3, false, false}, C64_KEYCODE_3},
    {{SDLK_4, false, false}, C64_KEYCODE_4},
    {{SDLK_5, false, false}, C64_KEYCODE_5},
    {{SDLK_6, false, false}, C64_KEYCODE_6},
    {{SDLK_7, false, false}, C64_KEYCODE_7},
    {{SDLK_8, false, false}, C64_KEYCODE_8},
    {{SDLK_9, false, false}, C64_KEYCODE_9},
    {{SDLK_w, false, false}, C64_KEYCODE_W},
    {{SDLK_a, false, false}, C64_KEYCODE_A},
    {{SDLK_z, false, false}, C64_KEYCODE_Z},
    {{SDLK_s, false, false}, C64_KEYCODE_S},
    {{SDLK_e, false, false}, C64_KEYCODE_E},
    {{SDLK_r, false, false}, C64_KEYCODE_R},
    {{SDLK_d, false, false}, C64_KEYCODE_D},
    {{SDLK_c, false, false}, C64_KEYCODE_C},
    {{SDLK_f, false, false}, C64_KEYCODE_F},
    {{SDLK_t, false, false}, C64_KEYCODE_T},
    {{SDLK_x, false, false}, C64_KEYCODE_X},
    {{SDLK_y, false, false}, C64_KEYCODE_Y},
    {{SDLK_g, false, false}, C64_KEYCODE_G},
    {{SDLK_b, false, false}, C64_KEYCODE_B},
    {{SDLK_h, false, false}, C64_KEYCODE_H},
    {{SDLK_u, false, false}, C64_KEYCODE_U},
    {{SDLK_v, false, false}, C64_KEYCODE_V},
    {{SDLK_i, false, false}, C64_KEYCODE_I},
    {{SDLK_j, false, false}, C64_KEYCODE_J},
    {{SDLK_m, false, false}, C64_KEYCODE_M},
    {{SDLK_k, false, false}, C64_KEYCODE_K},
    {{SDLK_o, false, false}, C64_KEYCODE_O},
    {{SDLK_n, false, false}, C64_KEYCODE_N},
    {{SDLK_p, false, false}, C64_KEYCODE_P},
    {{SDLK_l, false, false}, C64_KEYCODE_L},
    {{SDLK_q, false, false}, C64_KEYCODE_Q},
    {{SDLK_MINUS, false, false}, C64_KEYCODE_MINUS},
    {{SDLK_PERIOD, false, false}, C64_KEYCODE_PERIOD},
    {{SDLK_COMMA, false, false}, C64_KEYCODE_COMMA},
    {{SDLK_DOLLAR, false, false}, C64_KEYCODE_DOLLAR},
    {{SDLK_LESS, false, false}, C64_KEYCODE_LESS},
    {{SDLK_RIGHT, false, false}, C64_KEYCODE_RIGHT},
    {{SDLK_LEFT, false, false}, C64_KEYCODE_LEFT},
    {{SDLK_DOWN, false, false}, C64_KEYCODE_DOWN},
    {{SDLK_UP, false, false}, C64_KEYCODE_UP},
    {{SDLK_F1, false, false}, C64_KEYCODE_F1},
    {{SDLK_F3, false, false}, C64_KEYCODE_F3},
    {{SDLK_F5, false, false}, C64_KEYCODE_F5},
    {{SDLK_F7, false, false}, C64_KEYCODE_F7},
    {{SDLK_QUOTE, false, false}, C64_KEYCODE_QUOTE},
    {{SDLK_HOME, false, false}, C64_KEYCODE_HOME},
    {{SDLK_DELETE, false, false}, C64_KEYCODE_DEL},
    {{228, false, false}, C64_KEYCODE_LEFTARROW}, // 228 = ä
    {{252, false, false}, C64_KEYCODE_LEFTBRACKET},
    {{1073741824, false, false}, C64_KEYCODE_RIGHTBRACKET},
    // right alt
    {{SDLK_2, false, true}, C64_KEYCODE_AT},
    {{SDLK_3, false, true}, C64_KEYCODE_HASH},
    // shift
    {{SDLK_2, true, false}, C64_KEYCODE_QUOTEDBL},
    {{SDLK_5, true, false}, C64_KEYCODE_PERCENT},
    {{SDLK_6, true, false}, C64_KEYCODE_AMPERSAND},
    {{SDLK_8, true, false}, C64_KEYCODE_LEFTPAREN},
    {{SDLK_9, true, false}, C64_KEYCODE_RIGHTPAREN},
    {{SDLK_LESS, true, false}, C64_KEYCODE_GREATER},
    {{SDLK_QUOTE, true, false}, C64_KEYCODE_QUESTION},
    {{SDLK_1, true, false}, C64_KEYCODE_PLUS},
    {{SDLK_3, true, false}, C64_KEYCODE_ASTERISK},
    {{SDLK_7, true, false}, C64_KEYCODE_SLASH},
    {{SDLK_0, true, false}, C64_KEYCODE_EQUALS},
    {{SDLK_PERIOD, true, false}, C64_KEYCODE_COLON},
    {{SDLK_COMMA, true, false}, C64_KEYCODE_SEMICOLON},
    {{SDLK_DOLLAR, true, false}, C64_KEYCODE_POUND},
    {{SDLK_DELETE, true, false}, C64_KEYCODE_INS},
    {{SDLK_HOME, true, false}, C64_KEYCODE_CLR},
    {{1073741824, true, false}, C64_KEYCODE_EXCLAIM},
    {{228, true, false}, C64_KEYCODE_UPARROW},
    // modifier keys
    {{SDLK_LALT, false, false}, C64_KEYCODE_COMMODORE},
    {{SDLK_LSHIFT, false, false}, C64_KEYCODE_SHIFTLEFT},
    {{SDLK_RSHIFT, false, false}, C64_KEYCODE_SHIFTRIGHT},
    {{SDLK_LCTRL, false, false}, C64_KEYCODE_CTRL},
};
#endif
